"""empty message

Revision ID: 73bbec7b5ebe
Revises: c255cdf1d8c3
Create Date: 2022-11-07 11:02:27.237200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bbec7b5ebe'
down_revision = 'c255cdf1d8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cyclist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cyclist')
    # ### end Alembic commands ###
